"""initial migration

Revision ID: 86a6b83b4f20
Revises: 
Create Date: 2023-10-10 17:27:07.351192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a6b83b4f20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egg_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eggs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_collected', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['color'], ['egg_colors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eggs')
    op.drop_table('egg_colors')
    # ### end Alembic commands ###
