"""empty message

Revision ID: a22847a51450
Revises: 5e5850fdc4eb
Create Date: 2023-10-15 09:55:37.921390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22847a51450'
down_revision = '5e5850fdc4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('egg_color', sa.Integer(), nullable=True),
    sa.Column('date_hatched', sa.DateTime(), nullable=False),
    sa.Column('est_hatch', sa.Boolean(), nullable=False),
    sa.Column('date_acquired', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['egg_color'], ['egg_colors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hens')
    # ### end Alembic commands ###
