"""empty message

Revision ID: fb590235aeb8
Revises: a22847a51450
Create Date: 2023-10-15 10:03:28.040453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb590235aeb8'
down_revision = 'a22847a51450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hens', schema=None) as batch_op:
        batch_op.alter_column('date_hatched',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('date_acquired',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hens', schema=None) as batch_op:
        batch_op.alter_column('date_acquired',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('date_hatched',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
